Create Jenkins file
I still need to find a way to fix the issue that the packages are not being installed: 
Database\DatabaseConnection.cs(1,7): error CS0246: The type or namespace name 'Dapper' could not be found (are you missing a using directive or an assembly reference?) [C:\Program Files (x86)\Jenkins\workspace\test_multipleSCM_pipeline\sylectus-lib-sylectus-core\Sylectus.Core\Sylectus.Core\Sylectus.Core.csproj]